name: controle_financeiro
description: Um aplicativo de controle financeiro em Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.19.0
  cloud_firestore: ^4.11.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  uuid: ^4.0.0
  crypto: ^3.0.0
  path: ^1.8.0
  http_parser: ^4.0.0
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  fl_chart: ^1.0.0

    # Adicione ou verifique estas linhas para o Firebase

  firebase_auth: ^4.17.9 # Use a versão mais recente que for compatível

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png
